services:
  forge:
    container_name: forge
    #image: itzg/minecraft-server:java17
    build: ./minecraft.Dockerfile
    restart: unless-stopped
    user: minecraft
    environment:
      # https://itzg.github.io/docker-minecraft-docs/java/environment/#server
      SETUP_ONLY: "true"
      ENABLE_ROLLING_LOGS: "true"
      LOG_TIMESTAP: "true"
      ENABLE_AUTOPAUSE: "true"
      GENERATE_STRUCTURES: "false"
      SPAWN_NPCS: "false"
      SPAWN_PROTECTION: "0"
      STOP_SERVER_ANNOUNCE_DELAY: "60"
      ENABLE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "true"
      RCON_PASSWORD_FILE: "/run/secrets/rcon_password"
    secrets:
      - rcon-password

    volumes:
      - /opt/minecraft/servers/civfun:/data

      # https://itzg.github.io/docker-minecraft-docs/java/configuration/misc-options/#timezone-configuration
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    ports:
      - 25565:25565
    tty: true
    stdin_open: true

  backup:
    container_name: backup
    image: itzg/mc-backup
    restart: unless-stopped
    user: minecraft
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_PASSWORD_FILE: "/run/secrets/rcon_password"
    secrets:
      - rcon-password

    volumes:
      # mount the same volume used by server, but read-only
      - /opt/minecraft/servers/civfun:/data:ro
      # use a host attached directory so that it in turn can be backed up to external/cloud storage
      - /opt/minecraft/backups/civfun:/backups

      # https://itzg.github.io/docker-minecraft-docs/java/configuration/misc-options/#timezone-configuration
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    
    # share network namespace with server to simplify rcon access
    network_mode: "service:forge"
    depends_on:
      - forge
  
secrets:
  rcon-password:
    #TODO: https://anthonymineo.com/rotating-your-docker-secrets-can-be-easy-if-you-plan-for-it/
    environment: RCON_PASSWORD