services:
  forge:
    #container_name: forge
    #image: itzg/minecraft-server:java17
    image: civfun-forge:latest
    build: server
    restart: unless-stopped
    #user: minecraft
    environment:
      # https://itzg.github.io/docker-minecraft-docs/java/environment/#server
      #SETUP_ONLY: "true"
      INIT_MEMORY: 12G
      MAX_MEMORY: 12G
      MAX_TICK_TIME: -1
      ENABLE_ROLLING_LOGS: "true"
      LOG_TIMESTAP: "true"
      ENABLE_AUTOPAUSE: "true"
      GENERATE_STRUCTURES: "false"
      SPAWN_NPCS: "false"
      SPAWN_PROTECTION: "0"
      STOP_SERVER_ANNOUNCE_DELAY: "60"
      ENABLE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "true"
      RCON_PASSWORD_FILE: "/run/secrets/rcon-password"
      EXTRA_ARGS: "--universe ./universe/"

    secrets:
      # https://forums.docker.com/t/unable-set-docker-secret-file-ownership-permissions/31336
      - source: rcon-password
        target: rcon-password
        # This should be the UID and GID of the minecraft user
        uid: "1000"
        gid: "1000"
        mode: 0440

    volumes:
      - /opt/minecraft/servers/civfun:/data

      # https://itzg.github.io/docker-minecraft-docs/java/configuration/misc-options/#timezone-configuration
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    tty: true
    stdin_open: true

    deploy:
      resources:
        reservations:
          cpus: "7"
          memory: 13g

  backup:
    #container_name: backup
    image: itzg/mc-backup
    restart: unless-stopped
    #user: minecraft
    environment:
      INITIAL_DELAY: "7m"
      BACKUP_INTERVAL: "12h"
      RCON_PASSWORD_FILE: "/run/secrets/rcon-password"

    secrets:
      - source: rcon-password
        target: rcon-password
        # This should be the UID and GID of the minecraft user
        uid: "1000"
        gid: "1000"
        mode: 0440

    volumes:
      # mount the same volume used by server, but read-only
      - /opt/minecraft/servers/civfun:/data:ro
      # use a host attached directory so that it in turn can be backed up to external/cloud storage
      - /opt/minecraft/backups/civfun:/backups

      # https://itzg.github.io/docker-minecraft-docs/java/configuration/misc-options/#timezone-configuration
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    
    # share network namespace with server to simplify rcon access
    network_mode: "service:forge"
    depends_on:
      - forge
  
secrets:
  rcon-password:
    #TODO: https://anthonymineo.com/rotating-your-docker-secrets-can-be-easy-if-you-plan-for-it/
    environment: RCON_PASSWORD
